#!/usr/bin/env python3
import os
import sys
import shutil
import subprocess
from pathlib import Path

def is_storage0_path(p: Path) -> bool:
    s = str(p.resolve())
    prefixes = (
        "/storage/emulated/0/",
        "/sdcard/",
        "/storage/self/primary/",
    )
    return any(s.startswith(x) for x in prefixes)

def run(cmd, cwd: Path):
    print("$ " + " ".join(cmd) + f"  (cwd={cwd})")
    subprocess.check_call(cmd, cwd=str(cwd))

def sanitize_version(v: str) -> str:
    v = v.strip()
    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-")
    out = "".join(ch for ch in v if ch in allowed)
    if not out:
        raise SystemExit("ERROR: invalid version (allowed: letters/digits . _ -)")
    return out

def copy_project(src_root: Path, dst_root: Path):
    ignore = shutil.ignore_patterns("node_modules", "dist", ".git", "__pycache__", "*.pyc")
    if dst_root.exists():
        shutil.rmtree(dst_root)
    shutil.copytree(src_root, dst_root, ignore=ignore)

def js_escape_for_template(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

def collect_third_party_files(tp_root: Path):
    """
    Collect third-party JS files from your folder structure in a stable order.
    We embed the exact files present in your tree.
    """
    # Prefer "working" versions:
    # - AJV: only min bundle exists in your tree
    # - JSONEditor: min bundle
    # - ACE: core + mode-json + worker-json
    # - Chart.js: prefer min for smaller ALL; keep non-min if min missing
    ordered_rel = [
        "ajv/ajv7.bundle.min.js",
        "json-editor/jsoneditor.min.js",
        "ace/ace.js",
        "ace/mode-json.js",
        "ace/worker-json.js",
        "chartjs/chart.umd.min.js",   # prefer min
        "chartjs/chart.umd.js",       # fallback (will be skipped if min exists)
    ]

    files = []
    seen = set()

    for rel in ordered_rel:
        p = tp_root / rel
        if p.is_file():
            # If we already included chart.umd.min.js, skip chart.umd.js
            if p.name == "chart.umd.js" and (tp_root / "chartjs/chart.umd.min.js").is_file():
                continue
            if p not in seen:
                files.append(p)
                seen.add(p)

    # Also include any other *.js recursively (optional, but keeps ALL future-proof)
    for p in sorted(tp_root.rglob("*.js")):
        if p.name.endswith(".map"):
            continue
        if p in seen:
            continue
        files.append(p)
        seen.add(p)

    return files

def make_all_entry(src_dir: Path) -> Path:
    """
    Generate a temporary ESM entry that injects third_party as classic scripts (globals)
    and then re-exports the UI kit API.
    """
    tp_root = src_dir / "third_party"
    files = collect_third_party_files(tp_root) if tp_root.is_dir() else []

    parts = []
    parts.append("""// AUTO-GENERATED by build.py
// All-in-one bundle entry: inject third-party scripts as classic <script> tags
// to preserve window.* globals, then re-export ui-kit-0 API.

function __injectThirdParty(label, code) {
  if (typeof document === "undefined") return;
  const s = document.createElement("script");
  // classic script (NOT type=module) so it attaches to window
  s.text = code + "\\n//# sourceURL=" + label;
  document.head.appendChild(s);
}
""")

    parts.append(f"// Found {len(files)} third_party files\\n")

    for p in files:
        code = p.read_text(encoding="utf-8", errors="replace")
        label = "third_party/" + str(p.relative_to(tp_root)).replace("\\", "/")
        parts.append(f'__injectThirdParty("{label}", `{js_escape_for_template(code)}`);\n')

    parts.append('\nexport * from "./ui-kit-0.js";\n')

    entry_path = src_dir / "__bundle_all_entry.js"
    entry_path.write_text("".join(parts), encoding="utf-8")
    return entry_path

def main():
    root = Path(__file__).resolve().parent
    src_dir = root / "src"
    dist_dir = root / "dist"
    entry_core = src_dir / "ui-kit-0.js"

    if not src_dir.is_dir():
        raise SystemExit(f"ERROR: src/ not found next to {Path(__file__).name}")
    if not entry_core.is_file():
        raise SystemExit(f"ERROR: entry not found: {entry_core}")

    if len(sys.argv) != 2:
        raise SystemExit(f"Usage: {Path(__file__).name} <version>\nExample: {Path(__file__).name} 0.0.1")
    version = sanitize_version(sys.argv[1])

    name = "ui-kit-0"
    out_core_dev = f"{name}-{version}.js"
    out_core_min = f"{name}-{version}.min.js"
    out_all_dev  = f"{name}-{version}.all.js"
    out_all_min  = f"{name}-{version}.all.min.js"

    dist_dir.mkdir(parents=True, exist_ok=True)

    # Build in $HOME workspace if we're on storage0 (noexec)
    build_root = root
    building_in_home = is_storage0_path(root)
    if building_in_home:
        home = Path(os.environ.get("HOME", str(Path("~").expanduser()))).resolve()
        ws = home / ".uikit_release"
        ws.mkdir(parents=True, exist_ok=True)
        build_root = ws / f"build_{root.name}"
        copy_project(root, build_root)

    (build_root / "dist").mkdir(parents=True, exist_ok=True)

    # Generate ALL entry inside the build workspace (IMPORTANT)
    build_src = build_root / "src"
    all_entry = make_all_entry(build_src)

    # CORE dev (with sourcemap)
    run([
        "npx", "esbuild", "./src/ui-kit-0.js",
        "--bundle", "--format=esm", "--target=es2020",
        "--sourcemap",
        f"--outfile=./dist/{out_core_dev}",
    ], cwd=build_root)

    # CORE min (no sourcemap)
    run([
        "npx", "esbuild", "./src/ui-kit-0.js",
        "--bundle", "--format=esm", "--target=es2020",
        "--minify",
        f"--outfile=./dist/{out_core_min}",
    ], cwd=build_root)

    # ALL dev (with sourcemap)
    run([
        "npx", "esbuild", f"./src/{all_entry.name}",
        "--bundle", "--format=esm", "--target=es2020",
        "--sourcemap",
        f"--outfile=./dist/{out_all_dev}",
    ], cwd=build_root)

    # ALL min (no sourcemap)
    run([
        "npx", "esbuild", f"./src/{all_entry.name}",
        "--bundle", "--format=esm", "--target=es2020",
        "--minify",
        f"--outfile=./dist/{out_all_min}",
    ], cwd=build_root)

    # Clean generated entry (optional)
    try:
        (build_src / all_entry.name).unlink()
    except FileNotFoundError:
        pass

    # Copy results back if built in workspace
    if building_in_home:
        built_dist = build_root / "dist"
        for fn in (
            out_core_dev, out_core_dev + ".map", out_core_min,
            out_all_dev, out_all_dev + ".map", out_all_min
        ):
            p = built_dist / fn
            if p.is_file():
                shutil.copy2(p, dist_dir / fn)

    # Copy SBOM if present
    sbom_src = build_root / "src" / "sbom.json"
    if sbom_src.is_file():
        shutil.copy2(sbom_src, dist_dir / "sbom.json")

    print("\nDone:")
    print(f" - dist/{out_core_dev} (+ .map)")
    print(f" - dist/{out_core_min}")
    print(f" - dist/{out_all_dev} (+ .map)")
    print(f" - dist/{out_all_min}")
    if (dist_dir / "sbom.json").is_file():
        print(" - dist/sbom.json")

if __name__ == "__main__":
    main()